# Configuration defaults
# Settings are separated into hyperparameters for architecture, data, implementation and train/eval hyperparams
# These are defaults for a small test, not for the crammed model!
defaults:
  - arch: hf-bert-tiny
  - data: sanity-check-2
  - impl: torch-default
  - wandb: none
  - train: bert-base
  - _self_
  - override hydra/job_logging: custom

base_dir: outputs
hydra:
  sweep:
    dir: ${base_dir}/${name}/${now:%Y-%m-%d_%H-%M-%S}_${data.name}
  run:
    dir: ${base_dir}/${name}/${now:%Y-%m-%d_%H-%M-%S}_${data.name}
  job:
    chdir: True

seed: # Optional: Set initial seed
name: default # A name for this run [will be used for the summary table and outputs folder]

# Total and central computation budget in hours:
budget: 24
# debug implementation by running every loop just once:
dryrun: False

validation:
  enabled: True
  split: 4096
  interval: 1000
  max_batches:
  seed: 89
  fixed_masks: True

k_fold:
  enabled: False
  num_folds: 10
  current_fold: 1
  seed: 42
